plugins { id 'com.android.application' }
android {
    namespace 'com.royal.spencerianlab'
    compileSdk 36
    defaultConfig {
        applicationId 'com.royal.spencerianlab'
        minSdk 26
        targetSdk 36
        versionCode 11
        versionName '1.4.0'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
    buildTypes { release { minifyEnabled false } }
}
